---
- hosts: ubuntu_pi
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: SetTimezone
      import_tasks: tasks/set_timezone.yml
    - name: Bootstrap
      import_tasks: tasks/bootstrap.yml

  handlers:
    - name: restart timesyncd
      service:
        name: systemd-timesyncd
        state: restarted

    - name: Reboot pi
      reboot:
        msg: "Reboot initiated by Ansible"

    - name: reboot_and_resume
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
