---
- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Bootstrap
      import_tasks: bootstrap.yml
    - name: SetTimezone
      import_tasks: tasks/set_timezone.yml
    - name: Install_Lamp
      import_tasks: tasks/install_lamp.yml
    - name: Configure Apache
      import_tasks: tasks/apache_config.yml
    - name: Configure MySQL
      import_tasks: tasks/mysql_config.yml
    - name: Configure PHP
      import_tasks: tasks/php_config.yml
    - name: Create Database
      import_tasks: tasks/create_database.yml
    - name: Install phpMyAdmin
      import_tasks: tasks/install_phpmyadmin.yml
    - name: Install Sensor Tools
      import_tasks: tasks/install_sensor_tools.yml
    - name: Install graphing tools
      import_tasks: tasks/configure_graphs.yml
    - name: Install and Configure Flask
      import_tasks: tasks/configure_flask.yml
      
  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted

  - name: reload apache2
    service:
      name: apache2
      state: reloaded
    
  - name: restart timesyncd
    service:
      name: systemd-timesyncd
      state: restarted