---
- hosts: humidity_server
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Bootstrap
      import_tasks: bootstrap.yml
    - name: SetTimezone
      import_tasks: set_timezone.yml
    - name: Install_Lamp
      import_tasks: install_lamp.yml
    - name: Configure Apache
      import_tasks: apache_config.yml
    - name: Configure MySQL
      import_tasks: mysql_config.yml
    - name: Configure PHP
      import_tasks: php_config.yml
    - name: Create Database
      import_tasks: create_database.yml
    - name: Install phpMyAdmin
      import_tasks: install_phpmyadmin.yml
    - name: Install Sensor Tools
      import_tasks: install_sensor_tools.yml
    - name: Install graphing tools
      import_tasks: configure_graphs.yml
    - name: Install and Configure Flask
      import_tasks: configure_flask.yml
      
  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted

  - name: reload apache2
    service:
      name: apache2
      state: reloaded
    
  - name: restart timesyncd
    service:
      name: systemd-timesyncd
      state: restarted