---
- hosts: ubuntu_pi
  become: true
  vars_files: roles/common/vars/main.yml
  roles:
    - role: common
      
    
- hosts: ansible_pi
  become: true
  vars_files: roles/humidity/vars/main.yml
  roles:
    - role: humidity
      
...