---

- name: Install matplotlib, mysqlconnector, flask
  pip:
    name:
      - matplotlib
      - mysql-connector-python
      - flask
    state: latest

- name: Copy python programs 
  copy:
    src: "{{ item }}"
    dest: "~/"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0644'
  with_items:
      - files/variables.py
      - files/create_landscape_graph.py
      - files/create_portrait_graph.py
      - files/testemail.py
      - files/get_humidity.py
      - vars/main.yml

- name: Create job that will grab humidity every 20 minutes
  ansible.builtin.cron:
    user: "{{ default_user }}"
    name: "grab humidity"
    minute: "*/20"
    job: "python3 get_humidity.py"
    
- name: Create job that will create a new historical graph every hour
  ansible.builtin.cron:
    user: "{{ default_user }}"
    name: "create hourly historical graph"
    minute: "0"
    job: "python3 create_landscape_graph.py"
    
- name: Create job that will create a new historical graph every hour
  ansible.builtin.cron:
    user: "{{ default_user }}"
    name: "create hourly historical graph"
    minute: "1"
    job: "python3 create_portrait_graph.py"
...