---

- name: Create All Directories for Flask
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0755'
  with_items:
    - "~/flask"
    - "~/flask/templates"
    - "~/flask/static"
    - "~/flask/static/images"

- name: Copy Portrait Background Image for webpage
  copy:
    src: "{{ item }}"
    dest: "~/flask/static/images/"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0644'
  with_items:
    - files/ikaria_portrait.png
    - files/ikaria_landscape.png

- name: Copy favicon
  copy:
    src: "{{ item }}"
    dest: "~/flask/static/"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0644'
  with_items:
    - files/favicon.ico
    - files/style.css

- name: Copy main_flask.py into flask Directory
  copy:
    src: "{{ item }}"
    dest: "~/flask/"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0644'
  with_items:
    - files/main_flask.py
    - files/just_humidity.py

- name: Copy base.html into flask Directory
  copy:
    src: "{{ item }}"
    dest: "~/flask/templates/"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0644'
  with_items:
    - files/main.html
    - files/graph.html
    #- files/style_graph.css
...