---

- name: Install_Lamp
  import_tasks: install_lamp.yml
- name: Configure Apache
  import_tasks: configure_apache.yml
- name: Configure MySQL
  import_tasks: configure_mysql.yml
- name: Configure PHP
  import_tasks: configure_php.yml
- name: Create Database
  import_tasks: create_database.yml
- name: Install phpMyAdmin
  import_tasks: install_phpmyadmin.yml
- name: Install Sensor Tools
  import_tasks: install_sensor_tools.yml
- name: Install graphing tools
  import_tasks: configure_graphs.yml
- name: Install and Configure Flask
  import_tasks: configure_flask.yml
...