---

- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: reload apache2
  service:
    name: apache2
    state: reloaded
  
- name: reboot pi
  reboot:
    msg: "Reboot initiated by Ansible"
