---

- name: Install matplotlib, mysqlconnector, flask
  pip:
    name:
      - matplotlib
      - mysql-connector-python
      - flask
    state: latest

- name: Copy python programs 
  copy:
    src: "{{ item }}"
    dest: /home/{{ default_user }}/
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0644'
  with_items:
      - files/variables.py
      - files/import_mysql_to_matplotlib.py
      - files/create_portrait_graph.py
      - files/testemail.py
      - files/humidity_ansible.py
      - vars/main.yml

#- name: Copy python program to convert yaml to python
#  copy:
#    src: files/variables.py
#    dest: /home/{{ default_user }}/{{ repository }}/
#    owner: "{{ default_user }}"
#    group: "{{ default_group }}"
#    mode: '0644'



#- name: Install python program to grab mysql data
#  copy:
#    src: files/import_mysql_to_matplotlib.py
#    dest: /home/{{ default_user }}/{{ repository }}/
#    owner: "{{ default_user }}"
#    group: "{{ default_group }}"
#    mode: '0644'



#- name: Install python program to grab mysql data for portrait graph
#  copy:
#    src: files/create_portrait_graph.py
#    dest: /home/{{ default_user }}/{{ repository }}/
#    owner: "{{ default_user }}"
#    group: "{{ default_group }}"
#    mode: '0644'
...