---

- name: Create Humidity database
  mysql_db:
    name: humidity
    state: present

- name: Copy bme680_tbl to host
  copy:
    src: 'files/create_table.sql'
    dest: '/tmp/create_table.sql'

- name: Create bme680_tbl
  mysql_db:
    name: humidity
    state: import
    target: '/tmp/create_table.sql'
...